ATTR_MEANING = {'GP': 'games_played', 'ST': 'starts', 'ON': 'sub_on', 'OFF': 'sub_off', 'MIN': 'minutes',
                'Y': 'yellow_cards', 'YR': 'yellow/red_cards', 'R': 'red_cards', 'G': 'goals', 'A': 'assists',
                'SA': 'secondary_assists', 'S': 'shots', 'SOG': 'shots_on_goal', 'INT': 'interceptions',
                'CR': 'crosses', 'ACR': 'accurate_crosses', 'CC': 'chances_created', 'BLK': 'blocks', 'TKL': 'tackles',
                'TKLW': 'tackles_won', 'FC': 'fouls_committed', 'FS': 'fouls_suffered', 'P': 'passes',
                'AP': 'attempted_passes', 'ACRO': 'accurate_crosses_open_play', 'AW': 'aerials_won',
                'BCC': 'big_chances_created', 'BR': 'ball_recoveries', 'DR': 'dribbles', 'DW': 'duels_won',
                'EG': 'errors_lead_to_goal', 'ES': 'errors_lead_to_shot', 'IBS': 'shots_inside_box',
                'IBSOG': 'shots_on_goal_inside_box', 'IBG': 'goals_inside_box', 'OBS': 'shots_outside_box',
                'OBSOG': 'shots_on_goal_outside_box', 'OBG': 'goals_outside_box', 'AOG': 'assist_own_goals',
                'APW': 'assist_penalties_won', 'DSP': 'dispossessed', 'OWN': 'own_goals', 'TOUCH': 'touches',
                'TBOX': 'touches_in_box', 'PK': 'penalty_kicks_taken', 'PKG': 'penalty_kick_goals',
                'PKM': 'penalty_kick_misses', 'PKSVD': 'penalty_kicks_saved', 'FKCR': 'free_kick_crosses',
                'FKACR': 'free_kick_accurate_crosses', 'CRN': 'corners', 'CRNCR': 'corner_crosses',
                'CRNW': 'corners_won', 'FKS': 'free_kick_shots', 'FKSOG': 'free_kick_shots_on_goal',
                'FKG': 'free_kick_goals', 'GC': 'goals_conceded', 'CS': 'clean_sheets', 'SV': 'saves',
                'IBSV': 'saves_from_shots_inside_box', 'OBSV': 'saves_from_shots_outside_box',
                'AKS': 'accurate_keeper_sweeper', 'PKC': 'penalty_kicks_conceded', 'PKF': 'penalties_faced',
                'PKSV': 'penalty_saves', 'CL': 'clearances', 'ECL': 'effective_clearances', 'PUNCH': 'punches',
                'ALB': 'accurate_long_balls', 'ATB': 'accurate_through_balls', 'LMT': 'last_man_tackle',
                'TOFF': 'total_offside', 'BCM': 'big_chance_missed', 'BCS': 'big_chance_scored',
                'ATTDR': 'attempted_dribbles', 'AOP': 'assists_from_open_play', 'ASP': 'assists_from_set_play',
                'CCOP': 'chances_created_from_open_play', 'CCSP': 'chances_created_from_set_play', 'Team': 'team',
                'OPP': 'opponent', 'H/A': 'home_away', 'Form': 'formation', 'Player Name': 'player_name',
                'POS': 'position'}

